<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

/** @var \Magento\Customer\Block\Newsletter $block */
$om = \Magento\Framework\App\ObjectManager::getInstance();
$customerSession = $om->get('Magento\Customer\Model\Session');
$CustomerRepositoryInterface = $om->get('Magento\Customer\Api\CustomerRepositoryInterface');
$customer_id = $customerSession->getCustomer()->getId();
$customer = $CustomerRepositoryInterface->getById($customer_id);
$enable_subscription =  $customer->getCustomAttribute('review_reminder');
if($enable_subscription){
$enable_subscription =  $enable_subscription->getValue();
}else{
    $enable_subscription = "";
}

?>
<?= $block->getChildHtml('form_before') ?>
    <form class="form form-newsletter-manage" action="<?= $block->escapeUrl($block->getAction()) ?>" method="post" id="form-validate">
        <fieldset class="fieldset">
            <?= $block->getBlockHtml('formkey') ?>
            <legend class="legend"><span><?= $block->escapeHtml(__('Subscription option')) ?></span></legend><br>
            <div class="field choice">
                <input type="checkbox" name="is_subscribed" id="subscription" value="1" title="<?= $block->escapeHtmlAttr(__('General Subscription')) ?>"<?php if ($block->getIsSubscribed()): ?> checked="checked"<?php endif; ?> class="checkbox">
                <label for="subscription" class="label"><span><?= $block->escapeHtml(__('General Subscription')) ?></span></label>
				<br/><br/><br/>
				 <input type="checkbox" name="review_subscribed" id="review_subscribed" value="1" title="<?= $block->escapeHtmlAttr(__('Product Review Subscription')) ?>"<?php if ($enable_subscription == "" || $enable_subscription=="1") { ?> checked="checked"<?php } ?> class="checkbox">
                <label for="review_subscribed" class="label"><span><?= $block->escapeHtml(__('Product Review Subscription')) ?></span></label>
				
				
            </div>
            <?php /* Extensions placeholder */ ?>
            <?= $block->getChildHtml('customer.form.newsletter.extra') ?>
        </fieldset>
        <div class="actions-toolbar">
            <div class="primary"><button type="submit" title="<?= $block->escapeHtmlAttr(__('Save')) ?>" class="action save primary"><span><?= $block->escapeHtml(__('Save')) ?></span></button></div>
            <div class="secondary"><a class="action back" href="<?= $block->escapeUrl($block->getBackUrl()) ?>"><span><?= $block->escapeHtml(__('Back')) ?></span></a></div>
        </div>
    </form>
<?php /* Extensions placeholder */ ?>
<?= $block->getChildHtml('customer.form.newsletter.extra2') ?>
